// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer 1.0.45
//     Available from https://marketplace.visualstudio.com/items?itemName=MadsKristensen.VsixSynchronizer64
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SolutionFavorites
{
    using System;

    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string SolutionFavoritesString = "7a4b358f-2116-47f8-bbe5-130edf57af2a";
        public static Guid SolutionFavorites = new Guid(SolutionFavoritesString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int FavoritesFileContextMenu = 0x0003;
        public const int AddToFavoritesGroup = 0x0010;
        public const int FileEditGroup = 0x0060;
        public const int FileActionsGroup = 0x0070;
        public const int AddToFavorites = 0x0100;
        public const int RemoveFromFavorites = 0x0101;
        public const int OpenContainingFolder = 0x0105;
        public const int CopyFullPath = 0x0106;
    }
}
